apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightweight-go-app
  labels:
    app: lightweight-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lightweight-go-app
  template:
    metadata:
      labels:
        app: lightweight-go-app
    spec:
      containers:
      - name: lightweight-go-app
        image: yousefelhattab/project:latest
