apiVersion: v1
kind: Service
metadata:
  name: lightweight-go-app-service
spec:
  selector:
    app: lightweight-go-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
  type: NodePort

# use the curl <NodeIP>:30080 for checking 
