apiVersion: v1
kind: Service
metadata:
  name: lightweight-go-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: lightweight-go-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
